- hosts: all
  become: true
  tasks:
    - name: Install sudo on Debian/Ubuntu
      apt: 
        name: sudo
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - name: Install sudo on Arch Linux
      community.general.pacman: 
        name: sudo
      when: ansible_distribution == 'Archlinux'

    - name: Get GitHub keys
      ansible.posix.authorized_key:
        user: "{{ ansible_user_id }}"
        state: present
        key: "{{ item }}"
      loop: "{{ lookup('url', 'https://github.com/Tedyst.keys', wantlist=True) }}"
    - name: Disable root login over SSH
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
      notify:
        - restart sshd

    - name: Disable password login
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
      notify:
        - restart sshd

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted