- hosts: all
  tasks:
    - name: Install zsh on Debian/Ubuntu
      apt: 
        name: zsh
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - name: Install zsh on Arch Linux
      community.general.pacman: 
        name: zsh
      when: ansible_distribution == 'Archlinux'

    - name: Clone oh-my-zsh
      ansible.builtin.git:
        repo: https://github.com/robbyrussell/oh-my-zsh.git
        dest: .oh-my-zsh
        depth: 1
        version: HEAD
        force: true

    - name: Clone Tedyst/zsh to ~/.zsh
      ansible.builtin.git:
        repo: https://github.com/Tedyst/zsh.git
        dest: .zsh
        version: HEAD
        recursive: true
        remote: true

    - name: Verify if ~/.zsh/zshrc is linked to ~/.zshrc
      stat:
        path: "~/.zsh/zshrc"
      register: zshrc

    - name: Link ~/.zsh/zshrc to ~/.zshrc
      file:
        path: ~/.zshrc
        state: link
        src: ~/.zsh/zshrc
      when: not zshrc.stat.islnk is defined and zshrc.stat.islnk

    - name: Verify if ~/.oh-my-zsh/custom is a link
      stat:
        path: "~/.zsh/zshrc"
      register: ohmyzsh

    - name: Delete original ~/.oh-my-zsh/custom
      file:
        path: ~/.oh-my-zsh/custom
        state: absent
      when: not ohmyzsh.stat.islnk is defined and ohmyzsh.stat.islnk

    - name: Link ~/.zsh/oh-my-zsh-custom to ~/.oh-my-zsh/custom
      file:
        path: ~/.oh-my-zsh/custom
        state: link
        src: ~/.zsh/oh-my-zsh-custom
        force: true
      when: not ohmyzsh.stat.islnk is defined and ohmyzsh.stat.islnk
